name: sma
description: A new Flutter project.
version: 7.0.0

environment:
<<<<<<< HEAD
  sdk: ">=2.10.0 <3.0.0"
=======
  sdk:
>>>>>>> 074192e78bbd74fcc43b259d6d537f9176f4ae7e

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
<<<<<<< HEAD
  dio: 
=======
  dio: ^3.0.10
>>>>>>> 074192e78bbd74fcc43b259d6d537f9176f4ae7e
  intl: "^0.16.1"
  charts_flutter: ^0.9.0
  cupertino_icons: ^0.1.2
  path_provider: ^1.6.7
  sembast: ^2.4.0
  sentry: ^3.0.1
  flutter_bloc: ^3.2.0
  flutter_spinkit: "^4.1.2"
  font_awesome_flutter: ^8.8.1
  google_nav_bar: ^2.2.0
  url_launcher: ^5.4.2
  flutter_offline: ^0.3.0
  data_connection_checker: ^0.3.4
<<<<<<< HEAD
  # flutter_candlesticks: ^0.1.4
  syncfusion_flutter_charts:
  syncfusion_flutter_gauges: 
  flutter_svg: ^0.19.1
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  firebase_auth:
  google_sign_in:
=======
  flutter_candlesticks: ^0.1.4
  flutter_candlesticks_chart:
  syncfusion_flutter_charts:
>>>>>>> 074192e78bbd74fcc43b259d6d537f9176f4ae7e


dev_dependencies:
  flutter_launcher_icons: ^0.7.4

  flutter_test:
    sdk: flutter
    
flutter_icons:
  android: "launcher_icon" 
  image_path: "assets/icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/default.jpg
<<<<<<< HEAD
    - assets/images/
    - assets/icons/
=======
>>>>>>> 074192e78bbd74fcc43b259d6d537f9176f4ae7e

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
